<?php

return [
    // Batches expiring within this many days are flagged "near expiry".
    'expiry_warning_days' => (int) env('BOTIKA_EXPIRY_WARNING_DAYS', 30),
    // Number of past complete months used by the demand forecasting module.
    'forecast_history_months' => (int) env('BOTIKA_FORECAST_HISTORY_MONTHS', 12),

    // The 63 barangays of Bulan, Sorsogon (source: PhilAtlas / PSGC). Used for the address dropdown.
    'barangays' => [
        'A. Bonifacio',
        'Abad Santos',
        'Aguinaldo',
        'Antipolo',
        'Beguin',
        'Benigno S. Aquino',
        'Bical',
        'Bonga',
        'Butag',
        'Cadandanan',
        'Calomagon',
        'Calpi',
        'Cocok-Cabitan',
        'Daganas',
        'Danao',
        'Dolos',
        'E. Quirino',
        'Fabrica',
        'G. del Pilar',
        'Gate',
        'Inararan',
        'J. Gerona',
        'J. P. Laurel',
        'Jamorawon',
        'Lajong',
        'Libertad',
        'M. Roxas',
        'Magsaysay',
        'Managanaga',
        'Marinab',
        'Montecalvario',
        'N. Roque',
        'Namo',
        'Nasuje',
        'Obrero',
        'Osmeña',
        'Otavi',
        'Padre Diaz',
        'Palale',
        'Quezon',
        'R. Gerona',
        'Recto',
        'Sagrada',
        'San Francisco',
        'San Isidro',
        'San Juan Bag-o',
        'San Juan Daan',
        'San Rafael',
        'San Ramon',
        'San Vicente',
        'Santa Remedios',
        'Santa Teresita',
        'Sigad',
        'Somagongsong',
        'Taromata',
        'Zone I Poblacion',
        'Zone II Poblacion',
        'Zone III Poblacion',
        'Zone IV Poblacion',
        'Zone V Poblacion',
        'Zone VI Poblacion',
        'Zone VII Poblacion',
        'Zone VIII Poblacion',
    ],
];
